# Generated by Django 2.1.2 on 2018-10-05 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True)),
                ('subject_identifier', models.CharField(max_length=50, verbose_name='Subject Identifier')),
                ('subject_identifier_as_pk', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject_identifier_aka', models.CharField(editable=False, help_text='track a previously allocated identifier.', max_length=50, null=True, verbose_name='Subject Identifier a.k.a')),
                ('age_in_years', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], max_length=10)),
                ('a_citizen', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=30, verbose_name='Are you a Botswana Citizen?')),
                ('not_a_citizen', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('MARRIED', 'Marriage Certificate')], max_length=30, verbose_name='Are you married to to a Motswana?Do you have a Marriage certificate?')),
                ('literacy', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('Literate Witness', 'Literate Witness')], max_length=30, verbose_name='Literate , Illiterate , Or Otherwise')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=30, verbose_name='Marital Status?')),
                ('address', models.CharField(choices=[('ALONE', 'Alone'), ('PARTNER_SPOUSE', 'Partner/Spouse'), ('OTHER', 'Other'), ('NO_ANSWER', 'No Answer')], max_length=30, verbose_name='Who do you currently live with?')),
                ('screening_identifier', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Screening ID')),
                ('job_status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=30, verbose_name='Are you currently working?')),
                ('job_details', models.CharField(choices=[('Occassional_CasualEmployment_(piece_job)', 'Occassional_CasualEmployment(piece_job)'), ('Seasonal_Employment', 'Seasonal_Employment'), ('FormalWageEmployment(part-time)', 'Formal_Wage-Employment(full-time)'), ('FormalWageEmployment(part-time)', 'FormalWageEmployment(part-time)'), ('Self_Employed_Agriculture', 'Self-Employed_Agriculture'), ('Self_employed_Making_Money(full time)', 'Self-employed-Making-Money(full time)'), ('Self_employed_Making_Money(full time)', 'Self-Employed-Making-Money(part time)'), ('DWTA', 'Do not want to answer'), ('OTHER', 'Other')], max_length=20, verbose_name='In your job, what type of work do you do?')),
                ('job_description', models.CharField(choices=[('FARMER', 'Farmer (own land)'), ('FARM_WORKER', 'Farm work on employers land'), ('DOMESTIC_WORKER', 'Domestic worker'), ('PRIVATE_WORKER', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('FISHING', 'Fishing'), ('MINING', 'Mining'), ('TOURISM', 'Tourism/game parks'), ('SME', 'Working in shop / small business'), ('INFORMAL_SELLING', 'Informal selling'), ('COMMERCIAL_SEX_WORKER', 'Commercial sex work'), ('TRANSPORT', 'Transport (trucker/ taxi driver)'), ('FACTORY', 'Factory worker'), ('GAURD', 'Guard (security company)'), ('POLICE_SOLDIER', 'Police/Soldier'), ('CLERK', 'Clerical and office work'), ('GOVERNMENT_WORKER', 'Government worker'), ('TEACHER', 'Teacher'), ('HEALTHCARE_WORKER', 'Health care worker'), ('OTHER_PROFESSIONAL', 'Other professional'), ('DWTA', 'Do not want to answer'), ('OTHER', 'Other')], max_length=30, verbose_name='Describe the work that you door did in your most recent job.If you have more than one profession,choose the one you spend the most time doing.')),
                ('job_income', models.CharField(choices=[('none', 'None'), ('1-199 pula', '1-199 pula'), ('200-499 pula', '200-499 pula'), ('500-999 pula', '500-999 pula'), ('1000-4999 pula', '1000-4999 pula'), ('5000-10,000 pula', '5000-10,000 pula'), ('More than 10,000 pula', 'More than 10,000 pula'), ('DWTA', 'Do not want to answer')], max_length=30, verbose_name='In the past month, how much money did you earn?')),
                ('community_activity', models.CharField(choices=[('VERY_ACTIVE', 'VERY ACTIVE'), ('SOMEWHAT_ACTIVE', 'SOMEWHAT ACTIVE'), ('NOT_ACTIVE_AT_ALL', 'NOT ACTIVE AT ALL'), ('DWTA', 'DO NOT WANT TO ANSWER')], max_length=30, verbose_name='How active are you in community activities?')),
                ('voting', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('DWTA', "Don't want to answer"), ('NOT_APPLICABLE', 'Not applicable')], max_length=30, verbose_name='Did you vote in the last local government election?')),
                ('neighborhood_problems', models.CharField(choices=[('HIV_AIDS', 'HIV/AIDS'), ('Schools', 'Schools'), ('Sewer', 'Sewer'), ('Unemployment', 'Unemployment'), ('Roads', 'Roads'), ('Water', 'Water'), ('Other_specify', 'Other, specify'), ('House', 'House'), ('Malaria', 'Malaria')], max_length=30, verbose_name='What are the major problems in your neighborhood ?')),
                ('neighborhood_problems_solved', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('DWTA', "Don't want to answer")], max_length=30, verbose_name='If there is a problem in this neighborhood,do the adults work together in solving it?')),
                ('eligible', models.BooleanField(default=False, editable=False)),
                ('reasons_ineligible', models.TextField(editable=False, max_length=150, null=True, verbose_name='Reason not eligible')),
                ('consented', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
