# Generated by Django 2.1.2 on 2018-10-30 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tp_screening', '0002_delete_subjectscreening'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True)),
                ('subject_identifier', models.CharField(max_length=50, verbose_name='Subject Identifier')),
                ('subject_identifier_as_pk', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject_identifier_aka', models.CharField(editable=False, help_text='track a previously allocated identifier.', max_length=50, null=True, verbose_name='Subject Identifier a.k.a')),
                ('eligible', models.BooleanField(default=False, editable=False)),
                ('reasons_ineligible', models.TextField(editable=False, max_length=150, null=True, verbose_name='Reason not eligible')),
                ('consented', models.BooleanField(default=False, editable=False)),
                ('age_in_years', models.CharField(choices=[('None', 'None'), ('0-17', '18 and above')], max_length=15, verbose_name='1. How old are you?')),
                ('minor', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=35, verbose_name='2.Are you in the minor category?')),
                ('gaurdian_present', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=35, verbose_name='3. Do you have a gaurdian present?')),
                ('citizen_of_Botswana', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=15, verbose_name='4. Are you a citizen of Botswana?')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=35, verbose_name='5. Are you married?')),
                ('married_to_a_citizen', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NA', 'not_applicable')], max_length=35, verbose_name='6. Are you married to a Motswana?')),
                ('proof_of_marriage', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NA', 'not_applicable')], max_length=35, verbose_name='7. Do you have a proof of marriage?')),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('U', 'undetermined')], max_length=15, verbose_name='8. Select your Gender')),
                ('job_status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('NOT_APPLICABLE', 'Not applicable')], max_length=35, verbose_name='9. Are you currently working?')),
                ('job_details', models.CharField(choices=[('FARMER', 'farmer (own land)'), ('FARM_WORKER', 'farm work on employers land'), ('DOMESTIC_WORKER', 'domestic worker'), ('PRIVATE_WORKER', 'work in bar/ hotel/guest house/ entertainment venue'), ('FISHING', 'fishing'), ('MINING', 'mining'), ('TOURISM', 'tourism/game parks'), ('SME', 'working in shop / small business'), ('INFORMAL_SELLING', 'informal selling'), ('COMMERCIAL_SEX_WORKER', 'commercial sex work'), ('TRANSPORT', 'transport (trucker/ taxi driver)'), ('FACTORY', 'factory worker'), ('GAURD', 'guard (security company)'), ('POLICE_SOLDIER', 'police/Soldier'), ('CLERK', 'clerical and office work'), ('GOVERNMENT_WORKER', 'government worker'), ('TEACHER', 'teacher'), ('HEALTHCARE_WORKER', 'health care worker'), ('OTHER_PROFESSIONAL', 'other professional'), ('DWTA', 'do not want to answer'), ('OTHER', 'other')], max_length=35, verbose_name='10. In your main job what type of work do you do?')),
                ('literacy_status', models.CharField(choices=[('LITERATE', 'literate'), ('ILLETERATE', 'illeterate')], max_length=15, verbose_name='11. Are you Literate?')),
                ('literate_witness', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=35, verbose_name='12. Do you have a Literate witness?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
