# Generated by Django 2.1.2 on 2018-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0007_auto_20181031_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscreening',
            name='citizen_of_Botswana',
            field=models.CharField(choices=[('YES', 'yes'), ('YES', 'no')], max_length=15, verbose_name='5. Are you a citizen of Botswana?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='gaurdian_present',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not applicable')], max_length=35, verbose_name='4. Do you have a gaurdian present?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='literacy_status',
            field=models.CharField(choices=[('LITERATE', 'literate'), ('ILLITERATE', 'illiterate')], max_length=15, verbose_name='13. Are you Literate?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='literate_witness',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not applicable')], max_length=35, verbose_name='14. Do you have a Literate witness?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='married_to_a_citizen',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not_applicable')], max_length=35, verbose_name='7. Are you married to a Motswana?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='minor',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not applicable')], max_length=35, verbose_name='3.Are you in the minor category?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='proof_of_marriage',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not_applicable')], max_length=35, verbose_name='8. Do you have a proof of marriage?'),
        ),
    ]
