# Generated by Django 2.1.2 on 2018-11-21 14:34

import _socket
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.sites.managers
import edc_base.utils
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tp_screening', '0008_auto_20181121_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubjectScreening',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.')),
                ('slug', models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True)),
                ('subject_identifier', models.CharField(max_length=50, verbose_name='Subject Identifier')),
                ('subject_identifier_as_pk', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject_identifier_aka', models.CharField(editable=False, help_text='track a previously allocated identifier.', max_length=50, null=True, verbose_name='Subject Identifier a.k.a')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Reference')),
                ('screening_identifier', models.CharField(blank=True, db_index=True, editable=False, max_length=50, verbose_name='Screening ID')),
                ('eligible', models.BooleanField(default=False, editable=False)),
                ('reasons_ineligible', models.TextField(editable=False, max_length=150, null=True, verbose_name='Reason not eligible')),
                ('consented', models.BooleanField(default=False, editable=False)),
                ('age_in_years', models.IntegerField(verbose_name='1. How old are you?')),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=15, verbose_name='2. Select your Gender')),
                ('minor', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not applicable')], max_length=35, verbose_name='3.Are you in the minor category?')),
                ('gaurdian_present', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not applicable')], max_length=35, verbose_name='4. Do you have a gaurdian present?')),
                ('citizen_of_Botswana', models.CharField(choices=[('YES', 'yes'), ('YES', 'no')], max_length=15, verbose_name='5. Are you a citizen of Botswana?')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=35, verbose_name='6. Are you married?')),
                ('married_to_a_citizen', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not_applicable')], max_length=35, verbose_name='7. Are you married to a Motswana?')),
                ('proof_of_marriage', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not_applicable')], max_length=35, verbose_name='8. Do you have a proof of marriage?')),
                ('job_status', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('DNWTA', 'do not want to answer')], max_length=35, verbose_name='9. Are you currently working?')),
                ('job_details', models.CharField(choices=[('Occassional_CasualEmployment', 'occassional_casualemployment(piece_job)'), ('Seasonal_Employment', 'seasonal_employment'), ('Formal_Wage_Employment', 'formal_wage_employment(full-time)'), ('Formal_Wage_Employment', 'formal_wage_employment(part-time)'), ('Self_Employed_Agriculture', 'self_employed_agriculture'), ('Self_employed_Making_Money', 'self_employed_making_money(full time)'), ('Self_employed_Making_Money', 'self_employed_making_money(part time)'), ('DWTA', 'do not want to answer'), ('OTHER', 'other')], max_length=35, verbose_name='10. In your main job what type of work do you do?')),
                ('job_income', models.CharField(choices=[('NONE', 'none'), ('Level_one', '1-199 pula'), ('Level_two', '200-499 pula'), ('Level_three', '500-999 pula'), ('Level_four', '1000-4999 pula'), ('Level_five', '5000-10,000 pula'), ('Level_six', 'more than 10,000 pula'), ('DWTA', 'do not want to answer')], max_length=70, verbose_name='11. In the past month, how much money did you earnfrom work you did or received in payment?')),
                ('job_description', models.CharField(choices=[('FARMER', 'farmer (own land)'), ('FARM_WORKER', 'farm work on employers land'), ('DOMESTIC_WORKER', 'domestic worker'), ('PRIVATE_WORKER', 'work in bar/ hotel/guest house/ entertainment venue'), ('FISHING', 'fishing'), ('MINING', 'mining'), ('TOURISM', 'tourism/game parks'), ('SME', 'working in shop / small business'), ('INFORMAL_SELLING', 'informal selling'), ('COMMERCIAL_SEX_WORKER', 'commercial sex work'), ('TRANSPORT', 'transport (trucker/ taxi driver)'), ('FACTORY', 'factory worker'), ('GAURD', 'guard (security company)'), ('POLICE_SOLDIER', 'police/Soldier'), ('CLERK', 'clerical and office work'), ('GOVERNMENT_WORKER', 'government worker'), ('TEACHER', 'teacher'), ('HEALTHCARE_WORKER', 'health care worker'), ('OTHER_PROFESSIONAL', 'other professional'), ('DWTA', 'do not want to answer'), ('OTHER', 'other')], max_length=70, verbose_name='12. Describe the work that you do or did in your most recent job.If you have more than one profession,choose the one you spend the most time doing')),
                ('literacy_status', models.CharField(choices=[('LITERATE', 'literate'), ('ILLITERATE', 'illiterate')], max_length=15, verbose_name='13. Are you Literate?')),
                ('literate_witness', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('NOT_APPLICABLE', 'not applicable')], max_length=35, verbose_name='14. Do you have a Literate witness?')),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(primary_key=True, serialize=False)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.Site')),
            ],
            options={
                'verbose_name': 'historical subject screening',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelManagers(
            name='subjectscreening',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='screening_identifier',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Screening ID'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='age_in_years',
            field=models.IntegerField(verbose_name='1. How old are you?'),
        ),
    ]
